### ISSUE TITLE
Allow Mailhog to be started as a (Windows) Service

### ISSUE THREAD

**Issue by oers** [mailhog/MailHog#10]
It would be great, if we could start Mail Hog as a Windows Service.

There seems to be a golang package with support for services on different platforms:

https://bitbucket.org/kardianos/service/src

**Comment by ian-kent** [comment]
Having given it some thought, I don't think this should be implemented in MailHog. I think it would be more appropriate to be handle it outside MailHog, e.g. using a system process manager, Docker, websysd, etc.

Alternatively, if there really is a need to support services on Windows, perhaps it could just be a batch file to register/unregister/start/stop the service?

**Comment by oers** [comment]
MailHog can be run as a service under windows with : https://nssm.cc/

**Comment by delboy1978uk** [comment]
This is actually possible using Windows Task Scheduler. Create a new Basic Task, and you can select it to run daily, weekly, on startup, on login, etc. Hope this helps.

**Comment by noxidsoft** [comment]
> This is actually possible using Windows Task Scheduler. Create a new Basic Task, and you can select it to run daily, weekly, on startup, on login, etc. Hope this helps.

Still helpful on Windows 11, in 2023. (commented here due to this thread showing on google search top of first page)

**Comment by lycode-dev** [comment]
> This is actually possible using Windows Task Scheduler. Create a new Basic Task, and you can select it to run daily, weekly, on startup, on login, etc. Hope this helps.

If you find it bothersome that the CMD opens, you can configure the settings as follows. It will ask you to sign in with your user account:

<img width="484" alt="image" src="https://github.com/mailhog/MailHog/assets/140956703/22d91847-2c50-4c22-a0b5-20277c4bd7d3">
