### ISSUE TITLE
Switch to alpine for the docker image

### ISSUE THREAD

**Issue by lmakarov** [mailhog/MailHog#108]
Alpine based image is more than two times smaller than the standard (Debian based) one.
The resulting mailhog image size is 280.1 MB (using golang:1.7-alpine) vs 691.6 MB (using golang:1.7).

**Comment by AGhost-7** [comment]
I think that size is less important in this case. If you're going to use this for testing, you're probably going to need to use it for debugging, and using something you're familiar with is a better choice. I think a lot of people are more familiar with Debian.

**Comment by ian-kent** [comment]
Thanks @lmakarov, and thanks for #109 

Does the version provided by [Rockerfile](Rockerfile) help? It's only 15 MB, and is the 'official' one hosted at [Docker Hub](https://hub.docker.com/r/mailhog/mailhog/)

I think I'd be inclined to agree with @AGhost-7, but I won't be affected by it! [Dockerfile](Dockerfile) is intended as a development resource, while the Rockerfile version provides something aimed more at deployment.

**Comment by ian-kent** [comment]
I'll close this, I think it's been superseded by #118
