### ISSUE TITLE
Base64 email requires download to view contents

### ISSUE THREAD

**Issue by 123andy** [mailhog/MailHog#113]
When viewing a base64 email I must download the message to view the text.  Is this intended?  There are no attachments to the email.  It would greatly help my workflow to be able to preview the contents of the email in the web ui.

![image](https://cloud.githubusercontent.com/assets/7461553/18412590/03ce7972-7747-11e6-9395-418b93b58a2b.png)

**Comment by ian-kent** [comment]
Hopefully that will fix it - I'll get a new release out soon, let me know if it doesn't help!

**Comment by 123andy** [comment]
Hi Ian.  I just installed 1.0.0 with home brew and it still appears to be case sensitive on headers - e.g. `Content-type:` doesn't work, but `Content-Type` does.

**Comment by yukulele** [comment]
https://github.com/mailhog/MailHog-UI/pull/29
