### ISSUE TITLE
MailHog not working when using nginx proxy pass

### ISSUE THREAD

**Issue by Prazmok** [mailhog/MailHog#117]
I am using MailHog as a Docker container (using docker-compose) and for default configuration everything is OK. Unfortunately when I created Nginx proxy pass I get an error in browser console

```
VM61:35 WebSocket connection to 'ws://mailhog.sf3.dev:81/api/v2/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
```

I guess it is bad configuration problem but as far as I know there is no option to configure MailHog image for docker-compose.

**Comment by JSchlarb** [comment]
@Prazmok Add this to your nginx config ...  That should do the trick. You must ensure that your mime.types are well configured 

 ```
        chunked_transfer_encoding on;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_redirect off;
        proxy_buffering off;
```
More https://www.nginx.com/blog/websocket-nginx/

**Comment by ian-kent** [comment]
I've added a note to the configuration section of the docs - it's probably not in the most obvious place, but hopefully it'll help someone out!

**Comment by mkrsn** [comment]
Here is the equivalent config for the Apache

>     <LocationMatch /api/v2/websocket>
>         ProxyPass ws://127.0.0.1:3001/api/v2/websocket
>     </LocationMatch>

**Comment by opi** [comment]
Related comment about Apache proxy configuration https://github.com/mailhog/MailHog/issues/142#issuecomment-316062636

**Comment by rounak-codiant** [comment]
Below block worked for me

`  location ^~ /mailhog/ {
        chunked_transfer_encoding on;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://localhost:8025/;        
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_redirect off;
        proxy_buffering off;
  }
}`

**Comment by renanlucas07** [comment]
> Below block worked for me
> 
> ```
> location ^~ /mailhog/ {
>        chunked_transfer_encoding on;
>        proxy_set_header X-NginX-Proxy true;
>        proxy_pass http://localhost:8025/;        
>        proxy_set_header Upgrade $http_upgrade;
>        proxy_set_header Connection "upgrade";
>        proxy_http_version 1.1;
>        proxy_redirect off;
>        proxy_buffering off;
>  }
> ```

I used this inside a new server block together with my rails app configuration, i've added its own server_name and only `/` instead of `/mailhog/` as the location
