### ISSUE TITLE
It'd be practical to have an option which when enabled would require confirmation for each mail or sender address before images are loaded from remote servers

### ISSUE THREAD

**Issue by yarwelp** [mailhog/MailHog#125]

**Comment by ian-kent** [comment]
Could you give more info about the use case for this?

Since MailHog is designed as a testing tool (and should be within the total control of your environment - i.e. not accepting random mail from the internet), there shouldn't be any risk in it automatically loading images?

**Comment by eriknstr** [comment]
Test data could origin from a real mailbox.

**Comment by ian-kent** [comment]
Thanks - I'll add it to the list, but it won't be high priority

If you're not in control of the message content, it's not really what MailHog was designed for (there'll be some serious security risks in using MailHog to handle untrusted message data), so even if it didn't automatically load remote images, I wouldn't recommend using it unless you're generating the message content (e.g. testing an application which sends registration/welcome emails etc)

**Comment by tyndyll** [comment]
I don't see a practical way for this to be implemented at the moment. If there is still a pressing need for this please re-open and give some a walk through as to what you think this should look like
