### ISSUE TITLE
Bug with displaying email html

### ISSUE THREAD

**Issue by SergeySmile** [mailhog/MailHog#126]
Hello. I have a problem with displaying emails with html content.
For example i send email with **body**: `<b>афывафвы аывф аыфва</b>`
In **html tab** it looks like:
![](http://i.imgur.com/TGgPao0.png)
But in **text tab** it looks like:
![](http://i.imgur.com/ieLSSWj.png)

How can you see html tab is empty and it is impossible to view big emails with tables, pictures etc.

**Email source:**
`Content-Type: multipart/alternative; boundary="B_ALT_5833f9d4468f6"
Date: Tue, 22 Nov 2016 09:55:00 +0200
From: =?utf-8?Q?=d0=9f=d0=a3=d0=9f?= <smile.test@gmail.com>
Message-ID: 1W9PKKrDVo68J5I229Wy8dY-RwsnMkUG2u99mh8RakU=@mailhog.example
Mime-Version: 1.0
Received: from projects by mailhog.example (Go-MailHog)
          id 1W9PKKrDVo68J5I229Wy8dY-RwsnMkUG2u99mh8RakU=@mailhog.example; Tue, 22 Nov 2016 09:55:01 +0200
Reply-To: "smile.test@gmail.com" <smile.test@gmail.com>
Return-Path: <smile.test@gmail.com>
Subject: =?utf-8?Q?=d0=b0=d1=84=d1=8b=d0=b2=d0=b0?=
To: smile.test@gmail.com
User-Agent: CodeIgniter
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
X-Sender: smile.test@gmail.com

This is a multi-part message in MIME format.
Your email application may not support this format.

--B_ALT_5833f9d4468f6
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

афывафвы аывф аыфва

--B_ALT_5833f9d4468f6
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<b>афывафвы аывф аыфва</b>

--B_ALT_5833f9d4468f6--`

This bug reproduces only with cyrillic symbols inside body. If i don't use them - all is fine:
html tab:
![](http://i.imgur.com/UnzlGJd.png)

Plain text tab:
![](http://i.imgur.com/eB760gT.png)

**Email source:**
`Content-Type: multipart/alternative; boundary="B_ALT_5833fd49a4ddc"
Date: Tue, 22 Nov 2016 10:09:45 +0200
From: =?utf-8?Q?=d0=9f=d0=a3=d0=9f?= <smile.test@gmail.com>
Message-ID: nOah4Qk4Dya7feEXVfUsnpMjY7iHl0j9jA9Nz5GAycg=@mailhog.example
Mime-Version: 1.0
Received: from projects by mailhog.example (Go-MailHog)
          id nOah4Qk4Dya7feEXVfUsnpMjY7iHl0j9jA9Nz5GAycg=@mailhog.example; Tue, 22 Nov 2016 10:09:48 +0200
Reply-To: "smile.test@gmail.com" <smile.test@gmail.com>
Return-Path: <smile.test@gmail.com>
Subject: =?utf-8?Q?fsadf?=
To: smile.test@gmail.com
User-Agent: CodeIgniter
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
X-Sender:  smile.test@gmail.com

This is a multi-part message in MIME format.
Your email application may not support this format.

--B_ALT_5833fd49a4ddc
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

fasfdsdaf

--B_ALT_5833fd49a4ddc
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<b>fasfdsdaf</b>

--B_ALT_5833fd49a4ddc--`

**Comment by theonedemon** [comment]
up

**Comment by theonedemon** [comment]
up

**Comment by ian-kent** [comment]
What's sending the email?

This bit doesn't look quite right to me:
```
--B_ALT_5833f9d4468f6
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

афывафвы аывф аыфва
```

It gives the `Content-Transfer-Encoding` as `quoted-printable`, but the content doesn't look like it has been encoded? I'd have expected something like:

```
=D0=B0=D1=84=D1=8B=D0=B2=D0=B0=D1=84=D0=B2=D1=8B=20=D0=B0=D1=8B=D0=B2=D1=84=20=D0=B0=D1=8B=D1=84=D0=B2=D0=B0
```

Just tested that locally and with the content encoded correctly it works:

```
Content-Type: multipart/alternative; boundary="B_ALT_5833f9d4468f6"
Date: Tue, 22 Nov 2016 09:55:00 +0200
From: =?utf-8?Q?=d0=9f=d0=a3=d0=9f?= smile.test@gmail.com
Message-ID: 1W9PKKrDVo68J5I229Wy8dY-RwsnMkUG2u99mh8RakU=@mailhog.example
Mime-Version: 1.0
Received: from projects by mailhog.example (Go-MailHog)
id 1W9PKKrDVo68J5I229Wy8dY-RwsnMkUG2u99mh8RakU=@mailhog.example; Tue, 22 Nov 2016 09:55:01 +0200
Reply-To: "smile.test@gmail.com" smile.test@gmail.com
Return-Path: smile.test@gmail.com
Subject: =?utf-8?Q?=d0=b0=d1=84=d1=8b=d0=b2=d0=b0?=
To: smile.test@gmail.com
User-Agent: CodeIgniter
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
X-Sender: smile.test@gmail.com

This is a multi-part message in MIME format.
Your email application may not support this format.

--B_ALT_5833f9d4468f6
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

афывафвы аывф аыфва

--B_ALT_5833f9d4468f6
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

=D0=B0=D1=84=D1=8B=D0=B2=D0=B0=D1=84=D0=B2=D1=8B=20=D0=B0=D1=8B=D0=B2=D1=84=20=D0=B0=D1=8B=D1=84=D0=B2=D0=B0

--B_ALT_5833f9d4468f6--
```

**Comment by SergeySmile** [comment]
Thanks for feedback.

> What's sending the email?
Old php project which was writing on Codeigniter 2...

Ok, I understand what is wrong and will try to test content encoding.

But how does it work in gmail and thunderbird?...

Before start to use mailhog i have saved mails locally as files and opened it in thunderbird and it was looking nice.

**Comment by ian-kent** [comment]
> But how does it work in gmail and thunderbird?

Good point! I'm not sure what the expected behaviour is when the transfer encoding is 'quoted-printable' but the content isn't encoded. A quick glance at a probably old RFC seems to indicate only ASCII characters can be left unencoded, which wouldn't include cyrillic, but if Gmail and Thunderbird both accept it then maybe MailHog should too.

I'm just wary of fixing message formatting bugs against a known spec, since it could end up successfully rendering a message which a normal mail client couldn't.

**Comment by SergeySmile** [comment]
So what can i say: "Don't use Codeigniter 2" It's a joke ;D

Today, i tried to send email from Codeigniter 3 - and all is ok. 
I've compared Email library of codeigniter 2 and 3 version. They have different implementation of `_prep_quoted_printable`. Codeigniter 2 email library does not contain `quoted_printable_encode` inside. As a result - body is not encoded.

What about gmail and thunderbird, i think that they are detecting not encoded symbols and encode it.

**Comment by ian-kent** [comment]
Thanks for the info - glad its working on Codeigniter 3

I'll leave MailHog alone for this one - it suggests a client bug not a MailHog bug, but if it becomes a problem again let me know.
