### ISSUE TITLE
can't configure to run on a https domain

### ISSUE THREAD

**Issue by cameronbraid** [mailhog/MailHog#129]
I"m trying to run mailhog in openshift and have managed to get it mostly working.. smtp is working, but thw web ui isn't working, error is

﻿
VM51:35 Mixed Content: The page at 'https://example.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://example.com/api/v2/websocket'. This request has been blocked; this endpoint must be available over WSS.
VM51:35 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.(…)
https://example.com/api/v2/jim Failed to load resource: the server responded with a status of 404 ()

I tried setitng env

`MH_API_HOST=https://example.com/`

but its not being used in / 

source :

```
var apiHost = "";
      if(apiHost.length > 0 && !endsWith(apiHost, "/")) {
        apiHost += "/";
      }

```

**Comment by codablock** [comment]
I got the same error and had to switch to http to fix this.

**Comment by ian-kent** [comment]
I think this may have been fixed already, but maybe not in the latest release. I'll keep this open for now and will get a new release out asap.

**Comment by cameronbraid** [comment]
That would be great thanks

**Comment by cameronbraid** [comment]
Any idea of a eta for the release ?  

Also, can you please cut a release of your docker image too, thanks

**Comment by MWilkinson** [comment]
Hi @ian-kent
   I'm having this issue as well, it appears that the -api-host setting (MH_API_HOST env variable) is not being used in the UI template
Having done a bit of digging through the code (and I'm not that familier with Go) I think there are 2 possible solutions,
in MailHog-UI line 90 of web/web.go should map web.config.APIHost to APIHost, the alternative is to change line 152 of assets/templates/layout.html to use [: .config.APIHost :] rather than [: .APIHost :] 
The second change would obviously remove the need for APIHost in the map structure of web/web.go (circa line 90)

**Comment by timbrd** [comment]
Same problem here. I'm trying to get mailhog running on openshift as well.

**Comment by talawahtech** [comment]
Has anyone found a workaround for this in the meantime?

**Comment by cameronbraid** [comment]
Yeah,

I use a node proxy infront of mailhog that does a html rewrite like this

https://github.com/cameronbraid/mailhog-transformer-proxy

Cheers

Cameron

**Comment by talawahtech** [comment]
@cameronbraid thanks! I want to avoid adding any more dependencies at this point though.

@ian-kent How would I go about building a binary with the latest MailHog-UI changes? "go get github.com/mailhog/MailHog" seems to still have the old version and I am not super familiar with the go build process or the multi-repo setup that this project uses.

**Comment by kohenkatz** [comment]
@talawahtech You should be able to look at the `Makefile` to see what to run.

**Comment by dkaminski** [comment]
For those who have SMTP working on openshift, are you sending mail only from within your cluster or do you have a route from the outside set up as well? I have a route set up to target port 1025, but when sending mail in I get hung up on -  "SMTP: Connection reset by peer Unexpected EOF on SMTP connection".

**Comment by ian-kent** [comment]
> Also, can you please cut a release of your docker image too, thanks

@cameronbraid docker hub always builds from the latest master branch, so any changes on there should exist in the docker image (even if it says it's 0.2.1, it probably isn't, which I've just realised, and should probably fix)

> Having done a bit of digging through the code (and I'm not that familier with Go) I think there are 2 possible solutions,

@MWilkinson I'm fairly sure this line does it (http -> ws, https -> wss):
https://github.com/mailhog/MailHog-UI/blob/bb034fed0530baa12c3a9fae44b8aef39b370c3b/assets/js/controllers.js#L127
but you've made me doubt myself 😀

**Comment by talawahtech** [comment]
This is now working for me with the v1.0,0 docker tag. Thanks!

**Comment by tyndyll** [comment]
Closing based on @talawahtech's comment
