### ISSUE TITLE
My Mailhog stopped working after MAMP -> Valet

### ISSUE THREAD

**Issue by brothman01** [mailhog/MailHog#132]
I used MAMP and installed mailhog to test some WordPress mail being sent from a site on the MAMP server.  Mailhog worked like a charm with MAMP.  Now I use Valet, and while I like it, Mailhog doesn't work anymore.

Mailhog stopped working when I switched to valet, so my question is how can I make Mailhog work with Valet as well as it did with MAMP?

**Comment by brothman01** [comment]
WP_DEBUG has to be on.  (I don't know how it got turned off in the first place)

**Comment by tubiz** [comment]
Hi @brothman01 please how did you configured MAMP with Mailhog?
