### ISSUE TITLE
Docker Hub image not automatically built anymore

### ISSUE THREAD

**Issue by viossat** [mailhog/MailHog#133]
Currently, the latest image available on Docker Hub was built on `2016-09-04T18:23:47.194225883Z`. But some commits have been pushed since September, including the new Dockerfile based on Alpine. The automated build looks broken.

**Comment by ian-kent** [comment]
Thanks for letting me know - I'd forgotten to enable automated builds after switching back to Docker. Docker Hub should have the latest build now!

**Comment by viossat** [comment]
Thanks.

**Comment by zekenie** [comment]
@ian-kent It seems like the official image hasn't built in a while
