### ISSUE TITLE
Start using tags on docker hub

### ISSUE THREAD

**Issue by schnatterer** [mailhog/MailHog#146]
Right now, the only [tag available on docker hub](https://hub.docker.com/r/mailhog/mailhog/tags/) ist `latest`.
This makes using MailHog from docker hub risky.

That is,
`docker run mailhog/mailhog:latest` 
might return a different image on every call.

However, for example,
`docker run mailhog/mailhog:0.2.1` 
would return the same image on every call. This would make builds relying on MailHog repeatable and deterministic.

**Comment by ian-kent** [comment]
:+1: really good idea

it should be working now, so any future git tags should be saved as docker hub tags!

**Comment by schnatterer** [comment]
Thanks so much! 
Looking forward to the next release. Do you have a rough idea when it's going to be published?

**Comment by ian-kent** [comment]
It's already out as v1.0.0 😄 

And the tags seem to be working 🎉 

https://hub.docker.com/r/mailhog/mailhog/tags/

**Comment by schnatterer** [comment]
Great, That's wonderful news. Thanks again!

**Comment by Nklya** [comment]
They don't work for now =(
