### ISSUE TITLE
Raw.Data returned from API contains unexpected opening line-break when using maildir

### ISSUE THREAD

**Issue by talawahtech** [mailhog/MailHog#148]
I switched from memory storage to maildir storage because i ran into #121 but then I noticed that some of my end-to-end email test cases (where I send an email that ends up in MailHog, then query the API to verify the data that I sent) started failing. 

It looks like and extra "\r\n" is added to the beginning of the Raw.Data string in the API response when maildir storage is used. I don't know whether or not this is invalid from a MIME perspective, but it prevents my mail parser (mailparser 0.6.2 for Node.js) from parsing the message successfully. Plus I figured it might be unintentional since the behavior is different when memory storage is used.

**Comment by ian-kent** [comment]
I think this is related to mailhog/storage#7, I'll keep both open for now
