### ISSUE TITLE
auth for mail release

### ISSUE THREAD

**Issue by derwassi** [mailhog/MailHog#15]
There's no way to release mail via a smtp server that requires username/password.
Could you please add this?

Furthermore it would be great to specify default values for username/password/host/port via environment variables or command line options.

**Comment by ian-kent** [comment]
This is mostly implemented, username/password are supported for PLAIN and CRAMMD5 mechanisms, both via API and web UI.

There's also support for saving SMTP servers via the API and web UI when releasing a message (they can be reused for the rest of the MailHog session, but are lost when its restarted).

You can also load SMTP servers from a JSON file with the flag `-outgoing-smtp` or environment variable `MH_OUTGOING_SMTP` to persist between restarts.

**Comment by ian-kent** [comment]
I'll close this for now - the implementation should do everything you needed

I might come back to it and clean it up a bit in future, but the original intention for SMTP release was to forward messages to a real destination, which typically doesn't require authentication anyway.
