### ISSUE TITLE
Access issue

### ISSUE THREAD

**Issue by taharmk** [mailhog/MailHog#159]
hello every one,

i downloaded windowns 386 release of mailhog, i lunched it : 
****************************************************************************
2017/07/06 11:21:30 Using in-memory storage
2017/07/06 11:21:30 [SMTP] Binding to address: 0.0.0.0:1025
[HTTP] Binding to address: 0.0.0.0:8025
2017/07/06 11:21:30 Serving under http://0.0.0.0:8025/
Creating API v1 with WebPath:
Creating API v2 with WebPath:
********************************************************************
but when trying to connect to hhtp service it is diplaying error as follow : 
***********************

L'erreur suivante s'est produite en essayant d'accéder à l'URL : http://www.127.0.0.1:8025/

Impossible de déterminer l'adresse IP du nom d'hôte www.127.0.0.1

Le serveur DNS a retourné :

Name Error: The domain name does not exist.
**********************************************

any idea ??
i tried 0.0.0.0, localhost and 127.0.0.1 it is giving same error
thank you

**Comment by tyndyll** [comment]
The address should be http://127.0.0.1:8025 (no www). Adding the prefix convinces the browser that the address should be a domain name
