### ISSUE TITLE
Add daemon option for Linux

### ISSUE THREAD

**Issue by geerlingguy** [mailhog/MailHog#16]
It would be nice to be able to run mailhog as a daemon in Linux. I think the original MailHog had a `-daemon` option or something like that, but for the current version, the only way to run it in the background is to use nohup or pipe things somehow.

**Comment by ian-kent** [comment]
I'll close this now, but any init script contributions are still welcome :+1:

**Comment by geerlingguy** [comment]
Here's the `systemd` unit file I'm using for mailhog in my Ansible role (just for posterity):

```
[Unit]
Description=MailHog Email Catcher
After=syslog.target network.target

[Service]
Type=simple
ExecStart={{ mailhog_install_dir }}/mailhog
StandardOutput=journal
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

See: https://github.com/geerlingguy/ansible-role-mailhog/blob/master/templates/mailhog.unit.j2

**Comment by juampynr** [comment]
I followed [this guide](https://askubuntu.com/a/919059/166681) to set up the service in Ubuntu 16. Here are the steps:

1. Create `cat /etc/systemd/system/mailhog.service`.
2. Paste the following in it:
```
[Unit]
Description=MailHog service

[Service]
ExecStart=/usr/local/bin/mailhog

[Install]
WantedBy=multi-user.target
```

3. Start the service: `sudo systemctl start mailhog`.
4. Enable the service to run on boot: `sudo systemctl enable mailhog`
5. Restart.
6. Check that the web interface is running by opening `http://localhost:8025` in a browser.
7. Send a dummy email and verify that it shows up at the web interface with the following command:

```
php -r "\$from = \$to = 'your.emailaddress@gmail.com'; \$x = mail(\$to, 'subject'.time(), 'Hello World', 'From: '. \$from); var_dump(\$x);"
```

**Comment by macau23** [comment]
I would like a daemon option, because I want MailHog to run a sanity check on my options, and then background itself.

If I background it myself, I have to wait a little while then run a health check to know if it is okay.
