### ISSUE TITLE
Error when using sendmail_path with -S option in php.ini

### ISSUE THREAD

**Issue by gertmedia24** [mailhog/MailHog#167]
As per the MailHog readme, I updated my php.ini to use:
> sendmail_path = /usr/sbin/sendmail -S mail:1025

Now when trying to send mail getting error:

[Zend_Mail_Transport_Exception]  
  Unable to send mail. 

Also, running '/usr/sbin/sendmail -S mail:1025'  in the terminal says:

> sendmail: illegal option -- S

Some 'man' options here: http://www.sendmail.org/~ca/email/man/sendmail.html
Could any of these be used to get MailHog to work?

Any help much appreciated

**Comment by mfernea** [comment]
I got the same problem on Mac 10.12.6. I got it working by using `sendmail_path = /usr/sbin/sendmail -t -i` and adding `relayhost = 127.0.0.1:1025` in /etc/postfix/main.cf. Hope it helps!

**Comment by gertmedia24** [comment]
Thanks @mfernea !

Also came across this post (same thing pretty much):
https://gist.github.com/madalinignisca/55e3cbe1cbd9d3af2daea48b045eeb89

**Comment by mfernea** [comment]
I would reopen this as the documentation is not accurate. It's meant for Mac OSX as it mentions brew, but the -S option doesn't seem to work. Also, I'm not sure if this solution would be the prefered one.

**Comment by scottsb** [comment]
Note that using the `relayhost` option means that if you want to release an email you have to use an external SMTP server, as the local postfix agent will just loop the email back to Mailhog.

**Comment by boris-hocde** [comment]
Hi there,
I think the `sendmail -S` option is only available on Alpine docker images. It comes from the [busybox](https://busybox.net/) package.
With debian based images, you can go with SSMTP, that is straight-forward to set up.
