### ISSUE TITLE
Symantec Endpoint Protection quarantines MailHog as Malware

### ISSUE THREAD

**Issue by distributev** [mailhog/MailHog#185]
Please see the below screenshot

![mailhog-symantec](https://user-images.githubusercontent.com/19224635/33114839-f7e95a34-cf5e-11e7-80a3-0a30cf2e1d9e.jpg)

**Comment by tyndyll** [comment]
My suspicion is there isn't a lot we can do with this. Suggest you liase with your admin to see if it can be whitelisted
