### ISSUE TITLE
Assets as plain files (not precompiled)

### ISSUE THREAD

**Issue by wunderkind2k1** [mailhog/MailHog#196]
Hi,

i was looking for non binary assets the other day to make improvements to the ui. Can't find any? Am I blind or do I have a point?

Cheers, Sven

**Comment by Chiron1991** [comment]
MailHog is glued together from multiple other repositories. Frontend stuff is here: https://github.com/mailhog/MailHog-UI

**Comment by wunderkind2k1** [comment]
Ahkey. Thank your for pointing me to that project.
