### ISSUE TITLE
Show sender machine in web gui?

### ISSUE THREAD

**Issue by macau23** [mailhog/MailHog#207]
Great product, can I make a feature request?

It'd be a huge timesaver to show which machine the web interface were accepted from. A filter using that would help a lot too. Thanks.

**Comment by macau23** [comment]
Hi @ian-kent do you accept bounties for features?

**Comment by tyndyll** [comment]
@macau23 Can you explain a little more about what you are asking for?

**Comment by macau23** [comment]
@tyndyll I can't remove the waiting label from this issue, do you need more info?

**Comment by macau23** [comment]
@tyndyll I know someone who would be willing to sponsor this

**Comment by tyndyll** [comment]
@macau23 Drop me an email. My profile should have the email address
