### ISSUE TITLE
Disable release button

### ISSUE THREAD

**Issue by macau23** [mailhog/MailHog#208]
Disabling the release button as an option could be nice :)

**Comment by mwgamble** [comment]
Seconded. It feels like it would be very easy for the hand to slip and the finger to accidentally click the wrong button.

**Comment by macau23** [comment]
No reply, closing.

**Comment by mwgamble** [comment]
Not sure why this was closed. What's wrong with just leaving the feature request open indefinitely?

**Comment by mwgamble** [comment]
@macau23 Thanks for re-opening :)

**Comment by macau23** [comment]
I have moved to Mailpit. Closing.
