### ISSUE TITLE
I need help debugging a not working MailHog install

### ISSUE THREAD

**Issue by cig0** [mailhog/MailHog#218]
Hi,

I'm not sure if MailHog isn't working on my side out of my inability to correctly set it up, or if the issue resides in MH itself. I tried using the Docker image, and by installing it with Homebrew to no avail in neither of the cases.

Using Docker:
```
$ docker run -p 8025:8025 -p 1025:1025 -e MH_HOSTNAME='mailhog.local' mailhog/mailhog
2018/09/25 20:42:33 Using in-memory storage
2018/09/25 20:42:33 [SMTP] Binding to address: 0.0.0.0:1025
[HTTP] Binding to address: 0.0.0.0:8025
2018/09/25 20:42:33 Serving under http://0.0.0.0:8025/
Creating API v1 with WebPath:
Creating API v2 with WebPath:
```
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                           
392d8765b82f        mailhog/mailhog     "MailHog"           12 seconds ago      Up 11 seconds       0.0.0.0:1025->1025/tcp, 0.0.0.0:8025->8025/tcp
```

Using Homebrew:
```
$ brew services start mailhog
==> Successfully started `mailhog` (label: homebrew.mxcl.mailhog)
```
<img width="504" alt="screen shot 2018-09-25 at 17 20 06" src="https://user-images.githubusercontent.com/394089/46043485-87545300-c0ee-11e8-8a5e-8c614cd81993.png">
<img width="522" alt="screen shot 2018-09-25 at 17 20 28" src="https://user-images.githubusercontent.com/394089/46043492-8cb19d80-c0ee-11e8-944a-226454a2b27c.png">

In both cases, I can access MH’s web UI, but I have had no luck so far sending test emails to it.
For this purpose, I’m using _mhsendmail_:

```
$./mhsendmail --from="admin@mailhog.local" test@mailhog.local localhost:1025 -v
```

My reason to use MailHog is to test out Apache Airflow.
At first, I thought that I was possibly messing with their configurations, but in light of the tests using mhsendmail, maybe there's something else going here.

Thanks

**Comment by ap-wtioit** [comment]
The command Line you are citing seems to be missing the content of the email:
`$echo -n "From: App <app@mailhog.local>\nTo: Test <test@mailhog.local>\nSubject: Test message\n\nSome content!" | ./mhsendmail --from="admin@mailhog.local" test@mailhog.local localhost:1025 -v`

**Comment by cig0** [comment]
My gosh -- in retrospective looks so evident.

Only thing I had to add to your example is to escape the exclamation mark in `Some content!`

TYVM @ap-wtioit
