### ISSUE TITLE
Docs: Offering rancher catalog for mailhog

### ISSUE THREAD

**Issue by EugenMayer** [mailhog/MailHog#235]
Thanks for the great project. I bundled this one into a https://rancher.com/ catalog - if you like, include that in your docs https://github.com/EugenMayer/docker-rancher-extra-catalogs/tree/master/templates/mailhog

In any means, just thank you for this really hand piece of tooling!

**Comment by tyndyll** [comment]
Do you want to add this to the project so that we can automatically build and generate it on release?

**Comment by EugenMayer** [comment]
actually i did not really plan about this - just wanted to share, maybe for the docs - but at least saying thank you :)
