### ISSUE TITLE
Attachements in Base64 are not downloaded correctly

### ISSUE THREAD

**Issue by oers** [mailhog/MailHog#24]
Excerpt from the source:
  ------=_Part_106_2085203044.1420709065643
  Content-Type: application/pdf; name=2014826.001.pdf
  Content-Transfer-Encoding: base64
  Content-Disposition: attachment; filename=2014826.001.pdf
  
  JVBERi0xLjQKJaqrrK0KNCAwIG9iago8PAovQ3JlYXRvciAoQXBhY2hlIEZPUCBWZXJzaW9uIDEu
  MSkKL1Byb2R1Y2VyIChBcGFjaGUgRk9QIFZlcnNpb24gMS4xKQovQ3JlYXRpb25EYXRlIChEOjIw
  MTUwMTA4MTAyNDI1KzAxJzAwJykKPj4KZW5kb2JqCjUgMCBvYmoKPDwKICAvTiAzCiAgL0xlbmd0
  aCAxMSAwIFIKICAvRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0KeJydlndUU9kWh8+9N71Q
  khCKlNBraFICSA29SJEuKjEJEErAkAAiNkRUcERRkaYIMijggKNDkbEiioUBUbHrBBlE1HFwFBuW
  SWStGd+8ee/Nm98f935rn73P3Wfvfda6AJD8gwXCTFgJgAyhWBTh58WIjYtnYAcBDPAAA2wA4HCz
  ...

When Clicking the Download-Button it will just save the Base64 Characters in a textfile named 2014826.001.pdf and not create a valid pdf

**Comment by nexces** [comment]
I can confirm that. First error is the empty line in the beginning of the file. When i remove that line i can decode few bytes and there is another problem (maybe newline related).

**Comment by nexces** [comment]
It is newline related.
When i change newlines to from CRLF to LF and remove first empty line from downloaded data i can correctly base64 decode data into attachment.

**Comment by ian-kent** [comment]
Thanks @oers and @nexces, my bad! I "fixed" the newline handling in `github.com/mailhog/smtp`, but think I've probably applied it to content handled by the DATA command too

**Comment by oers** [comment]
Will the fix ensure, that the bas64chars are transformed to bytes and a valid PDF is downloaded?

**Comment by ian-kent** [comment]
I hope so :smile:

**Comment by nexces** [comment]
*BUMP*

Making attachments readable out-of-the-box would speed up my workflow ;)

**Comment by huglester** [comment]
+1 on this. attachments should be human readable !:) 

thanks for dependency-less mail catcher

**Comment by huglester** [comment]
Hello, can this be tagged maybe and build packages? thanks :)

**Comment by ian-kent** [comment]
Sorry, was hoping to get a few more fixes in before I did a release but run out of time! But no problem, I'll do it asap :smile:

**Comment by huglester** [comment]
Sure! Have them fixed then:)))  thought maybe you forgot about us :)))

**Comment by SalahAdDin** [comment]
it still does not enable us to download attachments.

**Comment by palatam** [comment]
this issue still exists with mailhog/mailhog:v1.0.1

downloaded files are not binary but the literal base64 string (also 3x in size)

**Comment by SalahAdDin** [comment]
> this issue still exists with mailhog/mailhog:v1.0.1
> 
> downloaded files are not binary but the literal base64 string (also 3x in size)

It seems this project is deprecated.
