### ISSUE TITLE
No any warnings in console when SMTP port is already taken

### ISSUE THREAD

**Issue by bocharsky-bw** [mailhog/MailHog#247]
If port 1025 is already taken - it does not show any warning on running. Well, UI works, but SMTP server does not catch any emails. Here's the output:

```
$ MailHog
2019/06/07 16:40:26 Using in-memory storage
2019/06/07 16:40:26 [SMTP] Binding to address: 0.0.0.0:1025
[HTTP] Binding to address: 0.0.0.0:8025
2019/06/07 16:40:26 Serving under http://0.0.0.0:8025/
Creating API v1 with WebPath:
Creating API v2 with WebPath:
[APIv2] GET /api/v2/jim
[APIv2] GET /api/v2/messages
[APIv2] GET /api/v2/websocket
```

I ran both Mailcatcher and then MailHog on Mac OS, the first catches all the emails, the second is always empty

**Comment by ns3777k** [comment]
i'd say that's impossible :-) for example if you try to run MailHog twice you'll get this error:

```
2019/09/23 00:19:53 Using in-memory storage
2019/09/23 00:19:53 [SMTP] Binding to address: 0.0.0.0:1025
[HTTP] Binding to address: 0.0.0.0:8025
2019/09/23 00:19:53 Serving under http://0.0.0.0:8025/
2019/09/23 00:19:53 [SMTP] Error listening on socket: listen tcp 0.0.0.0:1025: bind: address already in use
```

maybe you're running mailcatcher and mailhog on different interfaces?

**Comment by bocharsky-bw** [comment]
Yeah, sorry, Mailcatcher is on `127.0.0.1:1025` but MailHog is on `0.0.0.0:1025`, so same port but different host, my bad!
