### ISSUE TITLE
Provide a relative/local WebContext Path argument

### ISSUE THREAD

**Issue by oers** [mailhog/MailHog#25]
I tried to use Mailhog together with an apache-proxy. 

	ProxyPass /mailhog http://localhost:8025/
	ProxyPassReverse /mailhog http://localhost:8025/

Mailhog tries to resolve all resource absolute to the host:

http://localhost/images/hog.png

![image](https://cloud.githubusercontent.com/assets/1115563/5660962/556fbdac-9726-11e4-845f-6f5c74fd1c54.png)

I think mailhog needs an optional webcontext argument like -webcontext mailhog, which will then search all resources under /mailhog/.. instead of /

**Comment by ian-kent** [comment]
Just made all URLs relative in the web UI (for API calls and static content), means you can have a single MailHog instance proxied from different endpoints if you need to (or, continue to use the real MailHog UI as well as the proxied one).

I used nginx to test it which gave me some issues with the event stream - switched off proxy buffering and it worked. Thought I'd mention it in case you get the same with Apache.

**Comment by oers** [comment]
Sorry for giving feedback too late, but this doesn't seem to work,

```
Refused to load the script 'http://10.100.160.27/js/jquery-1.11.0.min.js' because it violates the following Content Security Policy directive: "script-src 'none'".
```
For http://10.100.160.27/mailhog

and 
```
	ProxyPass /mailhog http://localhost:8025/
	ProxyPassReverse /mailhog http://localhost:8025/
```

**Comment by burriko** [comment]
Just a +1 to say that I'm also trying to proxy through Apache, and have the same issue as oers with the latest version of MailHog.

**Comment by oers** [comment]
@ian-kent could you please reopen this issue? Or should I create a new one?

**Comment by paolomainardi** [comment]
I confirm the problem, any solution out there ?

**Comment by oers** [comment]
I am trying to build a solution for this in https://github.com/oers/MailHog-UI.
But it is not working as expected at the moment. I hope to create a fix for this, when I find the time :)

**Comment by ian-kent** [comment]
Closing this as I think it's been fixed by @oers contributions

**Comment by martens-web-netz-de** [comment]
I'm trying to proxy from sibling docker container:
```
version: '3'
services:
  web:
  ...
  mail:
    image: mailhog/mailhog
    environment:
      MH_UI_WEB_PATH: mail
```
with service "web" providing proxy:
```
<VirtualHost *:80>
	ProxyPreserveHost On
	ProxyPass /mail http://mail:8025/
	ProxyPassReverse /mail http://mail:8025/
</VirtualHost>
```
but all I get on http://web/mail is:
![grafik](https://user-images.githubusercontent.com/11268667/100742827-b1df7c00-33db-11eb-9e79-88d67f5d9e53.png)

I am happy about every hint...
