### ISSUE TITLE
Invalid instructions for deploying MailHog via command line

### ISSUE THREAD

**Issue by bocharsky-bw** [mailhog/MailHog#251]
On this page: https://github.com/mailhog/MailHog/blob/9b87c4cf3a6b9cca9c022999310b8e18829bf239/docs/DEPLOY.md it says run:

```bash
go get github.com/mailhog/MailHog
MailHog -h
```

Running this on my Ubuntu says:

> MailHog: Command not found

Any thoughts?

**Comment by Fale** [comment]
You probably are missing the Go bin path in your execution path

**Comment by bocharsky-bw** [comment]
Ah, yes, most probably it is! Though I just installed Go via APT and that's it, so looks like it wasn't added automatically. I think it would be good to add a note about it? And probably mention that you can execute the binary directly, for me the path was `~/go/bin/MailHog`

**Comment by tyndyll** [comment]
There are some additional instructions in Pull #192 which needs merged and then tweaked slightly.

**Comment by bocharsky-bw** [comment]
Let's merge it 👍
