### ISSUE TITLE
How to install on Linux / Ubuntu?

### ISSUE THREAD

**Issue by bocharsky-bw** [mailhog/MailHog#252]
Can anyone clarify installation for Ubuntu?

In the latest release: https://github.com/mailhog/MailHog/releases/tag/v1.0.0 - I see a few Linux installations:
- MailHog_linux_386
- MailHog_linux_amd64
- MailHog_linux_arm

But it does not work for my Ubuntu, I can download it but I don't know how to open it - the downloaded files have no extension part, and UIbuntu also does not suggest anything that would be able to open it.

> Built with Go - MailHog runs without installation on multiple platforms.

How? :) How to run it without installation?

In docs, you're saying that it's easier to install than Mailcatcher, but it's a controversial question for me :/ Any help are welcome!

**Comment by bocharsky-bw** [comment]
Partially might be resolved by #192

**Comment by ns3777k** [comment]
you got it running? i can help if you're still having troubles

**Comment by bocharsky-bw** [comment]
@ns3777k thanks! Well, still cannot figure out how to open those files without extension. If you could point me out how to to install MailHog using that `MailHog_linux_amd64` file for example  - would be cool!

**Comment by ns3777k** [comment]
there's no need to have an extension for a binary in linux :-) in fact, most binaries dont have an extension.

i assume you're on linux or mac, so:

1. download the file
2. open terminal
3. `cd [path_to_directory_with_binary]`
4. `chmod +x MailHog_linux_amd64`
5. `./MailHog_linux_amd64`

**Comment by bocharsky-bw** [comment]
Ah, just execute it! Lol, not even sure how I missed it... Thanks, it works this way :)
