### ISSUE TITLE
Some issues with dockerized environment

### ISSUE THREAD

**Issue by lispercat** [mailhog/MailHog#255]
hi,
I have two questions:
1) I see no files under maildir so looks like messages are not persisted 
2) When I leave http://localhost:8025 open for some time I see a bunch of email collected there, but as soon as click on "inbox", all the messages disappear.
3) When I send a message to mailhog with this configuration I get "Unable to store message" error

I can fix issue #2 if I remove storage related configuration from the docker

So here is the setup which doesn't work:
  mail:
    container_name: sp-mail
    image: mailhog/mailhog
    restart: always
    privileged: true
    tty: true
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - "/home/user/mailhog/maildir:/maildir"

So here is the setup that works:
  mail:
    container_name: sp-mail
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

Please see if you can spot some issues there.
Thanks!

**Comment by lispercat** [comment]
The issues is solved by providing user: root to the docker-compose file.
The reason for that is the folder /maildir has the root owner/group and 755 permission.
By default the Mailhog process is started as "mailhog" user so it doesn't have write permission to the /maildir folder. So we need to start it as a "root" user

**Comment by imclean557** [comment]
Alternatively, if your setup allows, you can change the ownership on the host.  In our case:

`chown -R 1000.1000 /data/storage/mailhog/data`
