### ISSUE TITLE
Mailhog with nginx reverse proxy not showing emails

### ISSUE THREAD

**Issue by sub1983** [mailhog/MailHog#256]
I have a mailhog and a nginx proxy in front but the problem is when accessing thru back end i can see the emails but thru the GUI its not showing up while doing inspect on the page shows its getting redirected to www.xxx.com/v2/messages rather than curl http://localhost:8025/api/v2/messages
will show messages from within the server

**Comment by ns3777k** [comment]
hey, can you show nginx configuration?

**Comment by subinmath** [comment]
server {
  listen 80;
  server_name myserver.com;


  location = /50x.html {
    root   /usr/share/nginx/html;
  }
  
#  location /api {
#    chunked_transfer_encoding on;
#    proxy_set_header X-NginX-Proxy true;
#    proxy_set_header Upgrade $http_upgrade;
#    proxy_set_header Connection "Upgrade";
#    proxy_http_version 1.1;
#    proxy_redirect off;
#    proxy_buffering off;
#    proxy_pass  http://localhost:8025/;
#  }

location / {
                proxy_pass      http://localhost:8025;
                proxy_set_header    Host             $host;
                proxy_set_header    X-Real-IP        $remote_addr;
                proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;
                proxy_set_header    X-Client-Verify  SUCCESS;
                proxy_set_header    X-Client-DN      $ssl_client_s_dn;
               # proxy_set_header    X-SSL-Subject    $ssl_client_s_dn;
               # proxy_set_header    X-SSL-Issuer     $ssl_client_i_dn;
                proxy_read_timeout 1800;
                proxy_connect_timeout 1800;
                chunked_transfer_encoding on;
                proxy_set_header X-NginX-Proxy true;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
                proxy_redirect off;
                proxy_buffering off;
        }  
  
}

**Comment by ns3777k** [comment]
well. that seems to be working fine. do you have other rules that rewrite /api/ somehow?

**Comment by ns3777k** [comment]
@subinmath seems like github stripped off /api part from your config :-)

you've got an error there:

```bash
location /api {
    ...
    proxy_pass http://localhost:8025/;
}
```

you replace `/api` to `/` in `proxy_pass`.
so you should just remove `/` from proxy pass to get everything working.

```
proxy_pass http://localhost:8025/; -> proxy_pass http://localhost:8025;
```

**Comment by subinmath** [comment]
thank you @ns3777k it worked

**Comment by sub1983** [comment]
the issue is fixed
