### ISSUE TITLE
Please make MailHog mobile friendly

### ISSUE THREAD

**Issue by shlima** [mailhog/MailHog#258]
Please make MailHog mobile friendly.

it is not possible to open an email on a mobile device right now

![0F46E20C-1040-4372-B5E6-0ED108FEA368](https://user-images.githubusercontent.com/2356771/66940362-7eae2200-f04d-11e9-825c-805407c7f395.jpeg)

**Comment by emadhegab** [comment]
is there any hope for this issue to be solved any soon?

**Comment by preetibellad** [comment]
@hieunv-0998 When this fix will be available for users on smartphone please?

**Comment by gwennlbh** [comment]
bruh
