### ISSUE TITLE
Here's how to get Mailhog working in Laravel

### ISSUE THREAD

**Issue by vesper8** [mailhog/MailHog#278]
Took me a few minutes to get it working so I thought I would share.

So first, if you're on a mac like I am you install with

```
brew install mailhog
```

Then start mailhog

```
brew services start mailhog
```

Then configure your mail server like this in your `.env`
```
### MAILHOG
MAIL_DRIVER=smtp
MAIL_HOST=0.0.0.0
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
### MAILHOG
```

Finally you can test that it is working.

Open up the Mailhog web interface at `http://127.0.0.1:8025/`

Then `php artisan tinker`

And you can run this command to send an email

```
Mail::send('errors.404', [], function ($message) { $message->to('abcd@xyz.com')->subject('this works!'); });
```

This will use the `errors/404.blade.php` template which you should have by default. You should see the mail arrive right away in Mailhog

**Comment by jartaud** [comment]
In case you have  **No hint path defined for [errors]** in tinker, replace the view.
