### ISSUE TITLE
Mega Project

### ISSUE THREAD

**Issue by pedromorgan** [mailhog/MailHog#30]
MaiHog is one part of the equation of using email..

A full circle would be to make "MailKit", and "mailhog" as a part of a full loop test env
- click a button and send a pass works
- a creation of account, and send email
- fabricate smtp logins for mobile,
- manage the postfix pretend server
- check vaction messages, and manage forwardings
- serialise emails to actuals files, like real postfix/dovecot
- simulate span and doss
- send mailings and in control of process
- create mailers, and newsgroups with easy opins outs
- focus on coporate client chain, and templates with const data
- mobile and tablet results,
- caching..
- the new cpanel for email
- rest interface for admin mailserver, forwardings and vatatins and mega issues

**Comment by pedromorgan** [comment]
https://github.com/daffodil/go-postfixadmin

**Comment by pedromorgan** [comment]
https://github.com/daffodil/go-mail2ajax

**Comment by pedromorgan** [comment]
https://github.com/daffodil/go-sms
Idea here is to send sms messages with a provicer and and a 
- outbound email to mobile
- inbound no to to mailbox
== plugin

**Comment by ian-kent** [comment]
This confused me completely, sorry! Not even sure what it all means... MailHog is a testing tool, nothing to do with postfix, sms or any other mail services?
