### ISSUE TITLE
Docker image isn't updated automatically

### ISSUE THREAD

**Issue by petercv** [mailhog/MailHog#31]
I installed the latest Docker image assuming it would contain the latest version of MailHog, however it doesn't. This is probably due how the project has been setup over multiple GitHub projects. Docker Hub only allows you to watch a single GitHub project so if a fix is done inside of one of the other projects and no changes are required in the main project, the docker image won't be rebuilt. 

An easy fix is to have some kind of version information somewhere in the main repository so that it is registered as a change. Because in other issues you mention version 0.1.3 which would contain the fix for HTML mail. But there is no file in the main repository that mentions this version number (or 0.1.1 and 0.1.2). After creating my own image with the Dockerfile the HTML issue is BTW fixed.

**Comment by ian-kent** [comment]
:+1: thanks, hadn't even considered it! I'll get it fixed asap (and I'll leave this open to remind me!)

**Comment by ian-kent** [comment]
I'd forgotten, but there is a [docs/RELEASES.md](RELEASES.md) I should have been updating, which would have trigger the rebuild. I'll update it now and (hopefully) remember to do it in future!
