### ISSUE TITLE
read emails through mailhog's smtp ?

### ISSUE THREAD

**Issue by epitre** [mailhog/MailHog#311]
Hello,

Do you know if it's possible to read emails through mailhog's smtp ?

I develop an app with php, and I use imap_open to access the emails in mailhog, I have an error :  
`Warning: imap_open(): Couldn't open stream`

Is it Mailhog that does not allow reading emails with smtp ?

**Comment by ThiefMaster** [comment]
You cannot read mails over SMTP - this is not how SMTP works. The protocols for reading emails are POP3/IMAP.

I don't think mailhog has either (and I don't think it would make any sense to add this)...

**Comment by epitre** [comment]
OMG, I did know the difference between SMTP and POP3/IMAP, but for whatever reason, I kept trying to read throug smtp :facepalm: 

Anyway, I am doing this because in my current development, I have to read an _IMAP_ mailbox.

For anyone trying to do the same stupid thing as me, I am now having a look at GreenMail ^^ https://greenmail-mail-test.github.io/greenmail/
