### ISSUE TITLE
mailhog/data failed to parse boundary

### ISSUE THREAD

**Issue by nvcnvn** [mailhog/MailHog#33]
Here I have a log with mime message: http://pastebin.com/iZ2KMdmR  
You can see that here https://github.com/mailhog/data/blob/master/message.go#L119  
MailHog assum that boundary should in the format of *boundary="..."* but it the spec I found its not necessary always https://tools.ietf.org/html/rfc2046#section-5.1.1

**Comment by ian-kent** [comment]
thanks @nvcnvn :+1:
