### ISSUE TITLE
could not resolve host :  github.com

### ISSUE THREAD

**Issue by Lazar996F** [mailhog/MailHog#345]
# cd .; git clone -- https://github.com/mailhog/MailHog /root/gocode/src/github.com/mailhog/MailHog
Cloning into '/root/gocode/src/github.com/mailhog/MailHog'...

fatal: unable to access 'https://github.com/mailhog/MailHog/': Could not resolve host: github.com
package github.com/mailhog/MailHog: exit status 128

ERROR: Service 'mailhog' failed to build

**Comment by tyndyll** [comment]
This looks like a DNS issue - the machine pulling the code could not resolve GitHub.com. Closing
