### ISSUE TITLE
500 Unrecognised command\r\n on Symfony

### ISSUE THREAD

**Issue by katethegreat-coder** [mailhog/MailHog#358]
Hello, I want to use Mailhog with the last Symfony version and I cannot visualize anything at http://localhost:8025/, whereas I can see that Mailhog processed emails in the Mailhog terminal. Could you help me to solve the problem? 

I have several error messages such as : 
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: INVALID] Started session, switching to ESTABLISH state
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Sent 35 bytes: '220 mailhog.example ESMTP MailHog\r\n'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Received 402 bytes: 'GET / HTTP/1.1\r\nHost: localhost:1025\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\nAccept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3\r\nAccept-Encoding: gzip, deflate\r\nConnection: keep-alive\r\nCookie: PHPSESSID=no0jrtfdgnsth2vl2ref9aup14\r\nUpgrade-Insecure-Requests: 1\r\n\r\n'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Processing line: GET / HTTP/1.1
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In state 1, got command 'GET', args '/ HTTP/1.1'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In ESTABLISH state
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Got unknown command for ESTABLISH state: 'GET'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Sent 26 bytes: '500 Unrecognised command\r\n'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Processing line: Host: localhost:1025
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In state 1, got command 'HOST:', args 'localhost:1025'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In ESTABLISH state
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Got unknown command for ESTABLISH state: 'HOST:'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Sent 26 bytes: '500 Unrecognised command\r\n'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Processing line: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In state 1, got command 'USER-AGENT:', args 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In ESTABLISH state
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Got unknown command for ESTABLISH state: 'USER-AGENT:'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Sent 26 bytes: '500 Unrecognised command\r\n'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Processing line: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In state 1, got command 'ACCEPT:', args 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In ESTABLISH state
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Got unknown command for ESTABLISH state: 'ACCEPT:'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Sent 26 bytes: '500 Unrecognised command\r\n'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Processing line: Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In state 1, got command 'ACCEPT-LANGUAGE:', args 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In ESTABLISH state
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Got unknown command for ESTABLISH state: 'ACCEPT-LANGUAGE:'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Sent 26 bytes: '500 Unrecognised command\r\n'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Processing line: Accept-Encoding: gzip, deflate
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In state 1, got command 'ACCEPT-ENCODING:', args 'gzip, deflate'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In ESTABLISH state
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Got unknown command for ESTABLISH state: 'ACCEPT-ENCODING:'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Sent 26 bytes: '500 Unrecognised command\r\n'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Processing line: Connection: keep-alive
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In state 1, got command 'CONNECTION:', args 'keep-alive'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In ESTABLISH state
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Got unknown command for ESTABLISH state: 'CONNECTION:'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Sent 26 bytes: '500 Unrecognised command\r\n'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Processing line: Cookie: PHPSESSID=no0jrtfdgnsth2vl2ref9aup14
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In state 1, got command 'COOKIE:', args 'PHPSESSID=no0jrtfdgnsth2vl2ref9aup14'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In ESTABLISH state
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Got unknown command for ESTABLISH state: 'COOKIE:'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Sent 26 bytes: '500 Unrecognised command\r\n'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Processing line: Upgrade-Insecure-Requests: 1
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In state 1, got command 'UPGRADE-INSECURE-REQUESTS:', args '1'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In ESTABLISH state
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Got unknown command for ESTABLISH state: 'UPGRADE-INSECURE-REQUESTS:'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Sent 26 bytes: '500 Unrecognised command\r\n'
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Processing line:
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In state 1, got command '', args ''
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] In ESTABLISH state
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] [PROTO: ESTABLISH] Got unknown command for ESTABLISH state: ''
2021/03/14 19:33:46 [SMTP 127.0.0.1:63416] Sent 26 bytes: '500 Unrecognised command\r\n'

**Comment by GardenRouteGold** [comment]
@katethegreat-coder how did you resolve this issue, I'm getting the same one ?

**Comment by pindab0ter** [comment]
This looks like what you'd see if you were to try to load `127.0.0.1:1025` in a browser, which is the SMTP server.

If you want the web interface, `127.0.0.1:8025` instead.

**Comment by lhall-amphibee** [comment]
I had the same problem, it was a Traefik misconfiguration that was indeed redirecting to the wrong port.

Thanks @pindab0ter :-)
