### ISSUE TITLE
Can't choose html preview for email

### ISSUE THREAD

**Issue by Khamliuk** [mailhog/MailHog#362]
Hey. tried both options: docker image and console tool and on both can't see html view for email

![image](https://user-images.githubusercontent.com/29075318/114032501-082a6300-9885-11eb-885b-6051bad9a955.png)

docker-image: mailhog/mailhog:v1.0.1
nikitakhamliuk@MacBook-Pro-Nikita-Khamliuk ~ % mailhog -version
MailHog version: 
(Idk but downloaded it today using brew)

**Comment by Khamliuk** [comment]
Fixed by myself

**Comment by Thomas-Richards-MoHC** [comment]
@Khamliuk 
> Fixed by myself

What did you have to do to get it to render as HTML?
