### ISSUE TITLE
Attachments - how to download them?

### ISSUE THREAD

**Issue by huglester** [mailhog/MailHog#38]
Hello,

I am attaching different files, as attachments, how I don't see anywhere in the UI, on where those attachments could be?

I see them in 'mimes', but when I try to download, they are not downloadable..

Thank you

**Comment by ian-kent** [comment]
Hi @huglester 

Could this be related to #24? Attachments are only shown in the MIME section at the moment, and they should be downloadable, but perhaps not in a particularly useful format.

I've been meaning to have at reimplementing MIME handling in the UI, its a bit :hankey: and doesn't support inline images etc either, just haven't had time yet - hopefully soon!

**Comment by huglester** [comment]
@ian-kent indded this seems very similar. I tried mailcatcher and emails are 'correctly' downloadable. I'll keep using mailcatcher for now, untill this issue is resolved.

btw, those images were 'attachments', not the inline, just in case!

duplicate of #24
