### ISSUE TITLE
Git Repo Fetch is Failing

### ISSUE THREAD

**Issue by yupthatguy** [mailhog/MailHog#394]
Trying to install mailhog on a fresh installation of Ubuntu Server 20.04 inside virtualbox, but I am getting an error

My steps:

```
sudo apt-get install golang-go
mkdir gocode
echo "export GOPATH=$HOME/gocode" >> ~/.profile
source ~/.profile
go get github.com/mailhog/MailHog
```

Resulting Error

```
# cd .; git clone -- https://github.com/mailhog/MailHog /root/gocode/src/github.com/mailhog/MailHog
Cloning into '/root/gocode/src/github.com/mailhog/MailHog'...
fatal: unable to access 'https://github.com/mailhog/MailHog/': gnutls_handshake() failed: Error in the pull function.
package github.com/mailhog/MailHog: exit status 128

```
Am I missing something?

**Comment by ap-wtioit** [comment]
This doesn't seem to be a Mailhog issue, but more an issue with your setup.

I can clone https://github.com/mailhog/MailHog without ssl errors. Most likely this was a temporary issue with github or you may have an https intercepting proxy between you and github that breaks https. You might also want check the dates on your systems (if they are before the current certs validity than https might also not work).

**Comment by yupthatguy** [comment]
You were absolutely right.  It was a virtualbox vs. wireguard issue. Simple solution, ditch virtualbox, install docker.  Thanks for the feedback.
