### ISSUE TITLE
Underscores being interpreted as spaces (%20) in HTML body links.

### ISSUE THREAD

**Issue by rosstimson** [mailhog/MailHog#41]
We are using Mailhog fairly extensively at work on test instances and members of development teams have been mentioning an issue with regards to underscores in links in the HTML body being wrongly interpreted as spaces.

For example if the email body has a link `email_activation` it gets interpreted as `email%20activation`.  This apparently happens for all links that use underscores as we also see this glitch with image names that contain underscores that then just 404.

I hope this makes sense and if we need to investigate further I will involve some of my developer colleagues to shine some more light on this.

**Comment by ian-kent** [comment]
Thanks @rosstimson, i'll investigate asap!

**Comment by rcrowe** [comment]
I can also replicate this issue if it's of any help.

**Comment by stevebelicha** [comment]
Yes I can replicate it too

**Comment by ian-kent** [comment]
thanks all, and sorry, haven't had a chance to look at this yet - hopefully will soon! (but PR's welcome if anyone does has a fix)

**Comment by jygastaud** [comment]
Bug confirmed here too.

@ian-kent any news regarding that issue? Can you drive us where to look at to try to fix it?

**Comment by ian-kent** [comment]
Sorry its taken a while to get around to looking at this - could anyone provide some example content please?

Just tried to reproduce it, but with a basic HTML e-mail it works as expected:
```
Subject: HTML test message
From: Foo <foo@bar.com>
To: Bar <bar@foo.com>
Mime-Version: 1.0
Content-Type: text/html; charset="ISO-8859-1"
Content-Transfer-Encoding: 7bit

<html>
<body>
<a href="http://iankent.uk/some_test_link">important link</a>
</body>
</html>
```

Wondering if it might be something to do with content encoding

**Comment by slonoed** [comment]
@ian-kent seems like problem in HTML renderer.

I use send to mailhog your html, and in Plan Text tab all OK
```
<html>
<body>
<a href=3D"http://iankent.uk/some_test_link">important link</a>
</body>
</html>
```

But in HTML tab
```
<html><head></head><body>
<a href="http://iankent.uk/some test link">important link</a>

</body></html>
```

**Comment by ian-kent** [comment]
Thanks @slonoed - can you provide the full SMTP message you used, I can't reproduce the bug with just the headers in the example I gave

**Comment by ian-kent** [comment]
I think this is fixed now - RFC2047 encoding was replacing a "_" with a " " before decoding, which is correct when applied to headers, but not the message body.

Please reopen if it hasn't been fixed :smile:
