### ISSUE TITLE
fix for issue #42 seems to have broken this

### ISSUE THREAD

**Issue by valguss** [mailhog/MailHog#47]
I get the following when trying to install on a new system:

# github.com/mailhog/MailHog
github.com/mailhog/MailHog/main.go:42: cannot use cb (type func("net/http".Handler)) as type func(*app.App) in argument to "github.com/mailhog/http".Listen
github.com/mailhog/MailHog/main.go:51: cannot use cb1 (type func("net/http".Handler)) as type func(*app.App) in argument to "github.com/mailhog/http".Listen
github.com/mailhog/MailHog/main.go:52: cannot use cb2 (type func("net/http".Handler)) as type func(*app.App) in argument to "github.com/mailhog/http".Listen

**Comment by ian-kent** [comment]
thanks @valguss - possibly missed a commit somewhere, I'll have a look asap

**Comment by ian-kent** [comment]
hopefully sorted now :)

**Comment by valguss** [comment]
That appears to have sorted it. Thanks :)
