### ISSUE TITLE
some escaping issue?

### ISSUE THREAD

**Issue by huglester** [mailhog/MailHog#50]
Hello again :)

I have spotted one more problem.
For example I get this email to mailhog:

```
to reset your password, please click <a href=3D"http://sentinel=
.app/change_password/13/2eVJjEic4h5oui6h2lJ8gzl9mdC4qzXQ">this link.</a>.=
```

it is the source. the soruce itself is the same in both mailcatcher and mailhog, but the HTML rendered in mailhog is currupt.

For example link ir not `change_password` but `change password` (without underscore)

Here are the headers from mailhog: 
```
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=utf-8
Date: Mon, 04 May 2015 09:53:14 +0000
From: CRM <admin@xxx.lt>
MIME-Version: 1.0
Message-ID: yrYwD4mk9KGB1YpNffAmtmBhLpb7Gt3kWz13y3BHWV8=@mailhog.example
Received: from sentinel.app by mailhog.example (Go-MailHog)
          id yrYwD4mk9KGB1YpNffAmtmBhLpb7Gt3kWz13y3BHWV8=@mailhog.example; Mon, 04 May 2015 12:53:14 +0300
Return-Path: <admin@xxx.lt>
Subject: Reset your account password.
To: admin@xxx.lt
```

Here are the headers from mailcatcher:
```
Message-ID: <7fee91ca7e7f3cba56bf1684e830c6b8@sentinel.app>
Date: Mon, 04 May 2015 09:53:40 +0000
Subject: Reset your account password.
From: CRM <admin@xxx.lt>
To: admin@xxx.lt
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
```

Not sure what else I can post :(

Thanks!

**Comment by ian-kent** [comment]
Thanks @huglester - is this is the same as #41? I'll try to reproduce using your message content, haven't been able to so far.

**Comment by ian-kent** [comment]
I think this is fixed now - RFC2047 encoding was replacing a "_" with a " " before decoding, which is correct when applied to headers, but not the message body.

Please reopen if it hasn't been fixed :smile:

**Comment by huglester** [comment]
Hello,

yes it is fixed now!:)
