### ISSUE TITLE
Open links in new window

### ISSUE THREAD

**Issue by TheShiftExchange** [mailhog/MailHog#52]
Hi,

MailHog is awesome.

Quick issue/question - is there a way to force all email links to be opened in a new window?

When I'm viewing my emails - if I click on a link in the email it opens it within the MailHog tab - I'd rather it just open a new window so MailHog stays as it was?

**Comment by ian-kent** [comment]
Thanks @TheShiftExchange 

There isn't at the moment, but it should be possible (ideally standard browser navigation should work, e.g. Cmd/Ctrl click)

I'll have a look when I get a chance, or PR's are welcome!
