### ISSUE TITLE
is web ui included in the binary ?

### ISSUE THREAD

**Issue by adrianmak** [mailhog/MailHog#55]
I downloaded the binary and ran in ubuntu.
Then accessed the web ui thru http://dev.local.net:8025
No response.

Then， netstat -nat, no 8025 port is listening

**Comment by ian-kent** [comment]
It should be, what log output do you get?

Without any configuration, MailHog should output something like this on startup:

```
~> ./MailHog_darwin_amd64
Using in-memory storage
[HTTP] Binding to address: 0.0.0.0:8025
[SMTP] Binding to address: 0.0.0.0:1025
Creating API v1
Creating API v2
```

**Comment by adrianmak** [comment]
I'm sorry. I forgot mailcatcher is running on the same box with port 1025.
Causing a conflict with MailHog stopped to run
