### ISSUE TITLE
MailHog sendmail not working as expected

### ISSUE THREAD

**Issue by stucki** [mailhog/MailHog#57]
I have a MailHog daemon running with default options.
I'm currently trying to use ```MailHog sendmail <email addr>``` to send a mail to MailHog.
(Later, my goal is to set PHPs ```sendmail_path = "/path/to/MailHog sendmail"```.)

However, this does not work as expected. ```MailHog sendmail``` is always trying to bind to ```localhost:1025```, which is already used by the MailHog daemon.

When I try using the separate ```mhsendmail``` binary, then it works just fine. So either I haven't understood the concept, or something is going wrong...

**Comment by ian-kent** [comment]
thanks @stucki, I'll have a look asap

**Comment by t0xicCode** [comment]
Turns out, the `MailHog sendmail` was introduced in commit 9dc6ad8ed404efc048f683a747c317ff8a0a99ae, which is after the latest tag, v0.1.7 (d9dc0b4edf558c398fc3fd679891f36cba61c2ce).

**Comment by ian-kent** [comment]
Sorry, that'd be my fault! Hopefully I should have the latest code released in in the next day or two!

**Comment by stucki** [comment]
Thanks!

**Comment by iefbr14** [comment]
See my pull request: https://github.com/mailhog/mhsendmail/pulls
for a bug fix to the mhsendmail code.  This code is shared and will fix the issue you are seeing.

**Comment by ian-kent** [comment]
Closing this as I think it's been fixed
