### ISSUE TITLE
Support for compression of HTTP responses

### ISSUE THREAD

**Issue by danielwhite** [mailhog/MailHog#61]
We're using MailHog for testing in an environment where testers and deployments are geographically distributed.

When the inbox has more than 50 messages, then refreshing the inbox can result in a response that can be 10MB or more. With compression, this reduces the response for a full 50 messages to a few hundred KB.

While we could put MailHog behind a real web-server, this would be an extra complexity that detracts from it being a simple drop-in solution.

This issue is primarily for visibility, and the relevant pull requests to support this are:
- mailhog/http#1
- mailhog/MailHog-UI#9

**Comment by ian-kent** [comment]
thanks @danielwhite :+1: merges are done so should work if building from source, or it'll be in the next release!

**Comment by ian-kent** [comment]
compression seems to break the event source connection, taking it back out while I investigate

**Comment by danielwhite** [comment]
Ouch. Sorry I didn't spot that. I'm happy to track down and fix the problem if nothing obvious has jumped out already.

**Comment by ian-kent** [comment]
I haven't had a chance to look properly yet, it may well be an issue with [goose](https://github.com/ian-kent/goose) rather than MailHog - but yeah I'd appreciate it if you do have time to investigate!

**Comment by tyndyll** [comment]
Closing this. There are other issues here that suggest extracting out attachments that I think may be the better solution to the problem for now
