### ISSUE TITLE
Can't follow links to X-Frame-Options SAMEORIGIN sites

### ISSUE THREAD

**Issue by jackc** [mailhog/MailHog#64]
Clicking a link in message body to any site that sets same origin policy fails. Mail area just goes blank. Appears to be from mail area being an iframe. It would be nice if clicking a link either followed the link normally or opened in new tab.

**Comment by ian-kent** [comment]
thanks @jackc, hopefully a straightforward fix, i'll have a look asap

**Comment by ian-kent** [comment]
this should be fixed by https://github.com/mailhog/MailHog-UI/commit/fc52cb6e8ed4311230e36addc341c6d3bc170592
