### ISSUE TITLE
Send Mail Programatically

### ISSUE THREAD

**Issue by AlaRuba** [mailhog/MailHog#67]
Hi,

I haven't seen any sample code in Go on how to send an email to the MailHog server. The RESTful API seems fuzzy on this, because it doesn't describe an endpoint I should hit. Is this possible in MailHog, because I don't want to send it from the command line.

**Comment by ian-kent** [comment]
Hi @AlaRuba 

There isn't an API endpoint for sending mail - MailHog can only receive messages via SMTP.
