### ISSUE TITLE
MailHog stops accepting mail

### ISSUE THREAD

**Issue by AlaRuba** [mailhog/MailHog#68]
Hi,

I noticed sometimes according to the logs, MailHog refuses to go from DATA state to MAIL state and refuses to accept new mail. Is there a way to force it to go mail state?

**Comment by ian-kent** [comment]
Hi @AlaRuba 

Could you provide example logs please? MailHog should switch to MAIL state once a message has been accepted. Forcing it to MAIL state would be the SMTP client sending `\r\n.\r\n` to signal the end of the message. If that doesn't happen for some reason, MailHog would be stuck in DATA.

If that sequence has been sent by the client there must be a bug somewhere, log output should help narrow it down.

**Comment by ian-kent** [comment]
Hi @AlaRuba - I'll close this for now, feel free to reopen the issue if it happens again (please include example logs)
