### ISSUE TITLE
API v2 not working?

### ISSUE THREAD

**Issue by huglester** [mailhog/MailHog#69]
Hello,

Is APIv2 working?

Sending delete to api/v2/messages does not work.
v1 works good.

Thanks

**Comment by ian-kent** [comment]
Hi @huglester 

APIv2 isn't (yet) a full reimplementation of APIv1, only features which needed a significant API change for the new UI have been added. You should use APIv1 if there isn't an APIv2 equivalent.

See https://github.com/mailhog/MailHog-Server/blob/master/api/v2.go#L29-L42.
