### ISSUE TITLE
Viewer not working correctly

### ISSUE THREAD

**Issue by Venorcis** [mailhog/MailHog#72]
Please see the screenshot below for what is happening to our mails in the MailHog UI. Note that when I download the EML and open it in e.g. Outlook, the mail looks fine.

![mailhog](https://cloud.githubusercontent.com/assets/3490872/11837999/8f23612c-a3e4-11e5-99b0-1bc7f06395d9.png)

The same happens for non-HTML mails by the way.

**Comment by ian-kent** [comment]
thanks @Venorcis, it was only looking for `Content-Transfer-Encoding` values in lowercase, should be fixed now
