### ISSUE TITLE
how to run mailhog on mac os

### ISSUE THREAD

**Issue by augustinex80** [mailhog/MailHog#86]
I downloaded MailHog_darwin_amd64 and MailHog_darwin_386. they both have no expanded-name. How can I run Mailbog.

Thank you.

**Comment by maijs** [comment]
@augustinex80 One of the easiest way to run mailhog on MacOS is to use mailhog formula for [Homebrew](http://brew.sh/).

Run `brew update && brew install mailhog` and you're done. If you require additional help with setting up mailhog with Homebrew, check out [this page](https://github.com/maijs/homebrew-mailhog).

**Comment by iamwithnail** [comment]
That answer should really be on the main page!  Completely non-obvious if you're coming into this for the first time.

**Comment by augustinex80** [comment]
docker？ sorry,  I asked a simple question. If docker is the right way. I will follow the docker's document. thank you! @maijs @iamwithnail

**Comment by ian-kent** [comment]
@augustinex80 not sure what you mean by no expanded-name, but the binaries on the release page should work on Mac OS (I've tested on 10.11.4)

@iamwithnail I've added the homebrew command to the readme :+1:

There's not really a right way - the binaries, docker and homebrew should all hopefully work.

**Comment by swrobel** [comment]
FYI, [the state of Mailhog's inclusion in Homebrew is in question](https://github.com/Homebrew/homebrew-core/issues/2501#issuecomment-231583316)

**Comment by ian-kent** [comment]
> FYI, the state of Mailhog's inclusion in Homebrew is in question

thanks, added in vendor directories, hopefully that'll help

**Comment by tobiashochguertel** [comment]
> That answer should really be on the main page! Completely non-obvious if you're coming into this for the first time.

This should be also added to the main-page of mailhog:

```
Open http://127.0.0.1:8025 and start using. (Give it couple of seconds to boot.)
```

or 

```

Usage
There are couple of ways to start MailHog:

Run brew services start mailhog if you have homebrew-services tap installed.
Run $(brew --prefix)/bin/MailHog & if you want to start it manually.
```

**Comment by gfonsecapilarte** [comment]
> > That answer should really be on the main page! Completely non-obvious if you're coming into this for the first time.
> 
> This should be also added to the main-page of mailhog:
> 
> ```
> Open http://127.0.0.1:8025 and start using. (Give it couple of seconds to boot.)
> ```
> 
> or
> 
> ```
> 
> Usage
> There are couple of ways to start MailHog:
> 
> Run brew services start mailhog if you have homebrew-services tap installed.
> Run $(brew --prefix)/bin/MailHog & if you want to start it manually.
> ```

I think this is exactly what is missing! thanks!

**Comment by sawirricardo** [comment]
> brew services start mailhog

Hey, I was also looking for this the brew services start mailhog for everone who dont want to mailhog everytime. Can we add this to the documentation?
