### ISSUE TITLE
file filesize.min.js.map missing

### ISSUE THREAD

**Issue by bardware** [mailhog/MailHog#91]
When I call `http://127.0.0.1:8025/#` the message `filesize.min.js.map missing` appears once in a while in the console.
I run `MailHog_windows_amd64.exe` as provided on github `MailHog v0.2.0`

![20160428_mailhog](https://cloud.githubusercontent.com/assets/802702/14881052/a992a1f0-0d32-11e6-9778-482a53398aa5.PNG)

**Comment by ian-kent** [comment]
thanks @bardware, should be fixed in the next release!
