### ISSUE TITLE
PHP Configuration hints

### ISSUE THREAD

**Issue by rfay** [mailhog/MailHog#99]
I had loads of trouble trying to get MailHog (with or without mhsendmail) to work with php-fpm (MacOS, homebrew, php5.6, mailhog 0.2)

I finally got it going with this in php.ini:

sendmail_path = "/usr/local/bin/mailhog sendmail test@example.org"

I can do a PR to add that simple recipe to the docs if you'll direct me where to put it. 

(I do see that hint in https://github.com/mailhog/mhsendmail/issues/3#issuecomment-127992203, which is where I got it, but that was closed.)

**Comment by ian-kent** [comment]
mailhog/mhsendmail#3 should have fixed it, assuming you have a `To:` header in the message

It could be worth adding some documentation to mention it - PHP config is mentioned in the (mhsendmail)[https://github.com/mailhog/mhsendmail]) readme, but currently without the e-mail address in the path

**Comment by rfay** [comment]
Hmm, maybe a new release for mhsendmail is the key fix? 

Note that I couldn't get mailhog 0.2.0 to work without the gratuitous test@example.com, but it works fine with it.

**Comment by ian-kent** [comment]
It might be that (really need to fix #71!), but if you've tried the `MailHog sendmail` one then it should use the latest mhsendmail for whichever version of MailHog you have installed

I'll do a new release after I've got through some open issues, hopefully that'll fix it!

**Comment by rfay** [comment]
OK, thanks for your work on this. MailHog is awesome. A real step forward in my dev workflow. Love the "delete all".

**Comment by ian-kent** [comment]
Thanks @rfay, and no problem, glad its useful :smile:

**Comment by SlayerBirden** [comment]
A tip to anyone wondering how to use Mailhog if it's running on a separate instance (not the php server) - for example on a separate docker container.

All you need to do is modify the **sendmail_path** on php server to include -S option:

    sendmail_path = /usr/sbin/sendmail -S mail:1025 -t

Where "_mail_" is the alias of my container running Mailhog.

**Comment by ian-kent** [comment]
:+1: thanks for the info, I've added the info to the MailHog README including a php.ini example

**Comment by Feyisayo** [comment]
I would like to add that using sendmail in debian docker containers seem to have issues. A good replacement is ssmtp.

Install using `apt install ssmtp`

ssmtp can be configured to use mailhog by editing `/etc/ssmtp/ssmtp.conf` like so:
```
root=yourmail@mail.com
# replace mailhog with the name of the mailhog service
mailhub=mailhog:1025
hostname=yourserver.example.com
FromLineOverride=YES
```
PHP can then be configured in php.ini like so:
`sendmail_path = /usr/sbin/ssmtp -t`

Some more details on ssmtp can be found [here](https://wiki.debian.org/sSMTP) 

This worked for me. I hope someone finds it useful
